/**
 * "This Couldn't Just Be Coincidence!" (Part 4): grid generation, cluster detection, and
 * placement-order recording.
 *
 * Belongs to: Group 2 (Clustering Illusions). Pure logic only: no DOM access, so it can be
 * read, reused, and tested in plain Node, mirroring clustering-illusion-grids.js (Part 1)
 * and random-streaks-stats.js (Part 3). The interactive layer lives in
 * this-couldnt-be-coincidence.js, which imports everything here.
 *
 * See notes/clustering_illusion_part_4_days_of_your_life_spec(rewrite).md for the full
 * design spec this module implements. Section references below point there.
 *
 * ----------------------------------------------------------------------------------
 * THE TASK MODEL (spec section 4)
 *
 * Two 20x20 grids, each with exactly B black cells (default 80, tunable 60-90). One grid
 * is generated by a uniform random process (generateRandomGrid); the other by a genuinely
 * non-random, spatially-clustering process (generateLocalAttractionGrid). Both processes
 * are exposed as ordinary functions -- neither ever edits cells after generation to
 * "insert" a pattern by hand (spec section 16, section 44: this would misrepresent the
 * process and undermine the exhibit's honesty).
 *
 * A "qualifying cluster" (spec section 6) is a completely filled k*k square, k >= 2.
 * Larger squares (k >= 3) are a bonus tier riding the exact same detection pass (spec
 * section 7) -- there is no separate rule or separate density tuning for them.
 *
 * ----------------------------------------------------------------------------------
 * PLACEMENT ORDER (spec section 11, section 14)
 *
 * Both generators record, for every black cell, the step index (0-based) at which it was
 * placed. This is what drives the rewind/scrub exploration control: replaying placement
 * order 0..B-1 replays each grid's actual construction history. The random generator's
 * order carries no spatial information (cells appear in an arbitrary sequence unrelated to
 * their neighbors); the local-attraction generator's order is the literal sequence in
 * which the biased sampler chose each cell, so scrubbing it visibly shows clusters growing
 * from seeds. Cells inserted by the repair fallback (spec section 12) are always given
 * placement indices AFTER every organically-placed cell, and are flagged separately, so the
 * scrubber never implies a repaired cell "grew" from the biased process -- it did not.
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Grid side length (spec section 4). Grid size does not meaningfully affect the cluster
 *  probabilities at a matched density -- confirmed by simulation during design -- so this
 *  is fixed at a clean, easy-to-read round number rather than tuned. */
export const GRID_SIZE = 20;
export const CELL_COUNT = GRID_SIZE * GRID_SIZE; // 400

/** Density slider range and default (spec section 16). */
export const MIN_BLACK_CELLS = 60;
export const MAX_BLACK_CELLS = 90;
export const DEFAULT_BLACK_CELLS = 80;
export const DENSITY_STOPS = [60, 70, 80, 90];

/**
 * Local-attraction coupling strength (spec section 12). Chosen by simulation: at lambda =
 * 0.7, ~96% of organically-generated grids contain a qualifying square with no repair
 * needed, averaging ~3.6 squares per grid, while the largest connected component averages
 * only ~11 of 80 black cells -- clumpy and structured-looking without collapsing into one
 * solid mass. See the design conversation log / references.md for the full sweep table.
 */
export const DEFAULT_LAMBDA = 0.7;

/** Safety cap on the "try random grids until one qualifies" search (spec section 9). At
 *  B=80 roughly 41% of random grids qualify on their own, so this is reached only if the
 *  RNG is behaving very unusually; it exists purely so a pathological run can never hang
 *  the page. */
export const MAX_RANDOM_ATTEMPTS = 500;

// ---------------------------------------------------------------------------
// Cell indexing helpers
// ---------------------------------------------------------------------------

/** Row-major cell index for (row, col), both 0-based. */
export function cellIndex(row, col, gridSize = GRID_SIZE) {
    return row * gridSize + col;
}

/** True if a cell at (row, col) is black in `cells`, treating out-of-bounds as white. This
 *  lets square-completion checks near an edge just read as "not a square" instead of
 *  needing separate bounds-checking at every call site. */
function isBlackAt(cells, gridSize, row, col) {
    if (row < 0 || row >= gridSize || col < 0 || col >= gridSize) return false;
    return cells[cellIndex(row, col, gridSize)] === 1;
}

// ---------------------------------------------------------------------------
// Random generator (spec section 10)
// ---------------------------------------------------------------------------

/**
 * Fisher-Yates shuffle, in place. Uniform as long as `rand` is uniform on [0, 1). Mirrors
 * clustering-illusion-grids.js's shuffleInPlace exactly.
 */
export function shuffleInPlace(array, rand = Math.random) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(rand() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

/**
 * A uniformly random arrangement of exactly `blackCells` black cells out of `gridSize`^2,
 * every subset equally probable (spec section 10). Never inspected, filtered, or nudged --
 * `findQualifyingRandomGrid` below handles selection by discarding and redrawing whole
 * grids, never by editing one.
 *
 * placementOrder[i] = the cell index placed at step i, in the order the shuffle produced
 * it. This carries no spatial meaning for the random model -- that lack of structure is
 * exactly what the rewind scrubber is meant to make visible.
 *
 * @returns {{cells: Uint8Array, placementOrder: number[]}}
 */
export function generateRandomGrid({ gridSize = GRID_SIZE, blackCells = DEFAULT_BLACK_CELLS, rand = Math.random } = {}) {
    const cellCount = gridSize * gridSize;
    const indices = Array.from({ length: cellCount }, (_, i) => i);
    shuffleInPlace(indices, rand);

    const placementOrder = indices.slice(0, blackCells);
    const cells = new Uint8Array(cellCount);
    for (const idx of placementOrder) cells[idx] = 1;

    return { cells, placementOrder };
}

/**
 * Repeatedly draws fresh random grids (never editing one) until one contains at least one
 * qualifying square, or `maxAttempts` is reached (spec section 9). Every draw is a true,
 * unedited call to generateRandomGrid -- this is legitimate conditional sampling, not
 * pattern insertion: the DISPLAYED grid is an actual draw from the true random generator,
 * selected by a documented, disclosed criterion (spec section 22).
 *
 * The returned `attempts` count is exactly what the exhibit's honest try-count line (spec
 * section 9, section 15) reports to the visitor -- it must never be replaced with a
 * hardcoded or illustrative number (spec section 32's acceptance criteria).
 *
 * IMPORTANT: any statistical null distribution (the "at least this clustered" comparison,
 * spec section 20/24) must be built from the UNCONDITIONED generateRandomGrid output, never
 * from grids pre-filtered through this function -- see coincidence-stats.js.
 *
 * @returns {{cells: Uint8Array, placementOrder: number[], attempts: number, analysis: ReturnType<typeof analyzeClusters>}}
 */
export function findQualifyingRandomGrid({
    gridSize = GRID_SIZE,
    blackCells = DEFAULT_BLACK_CELLS,
    rand = Math.random,
    maxAttempts = MAX_RANDOM_ATTEMPTS
} = {}) {
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        const { cells, placementOrder } = generateRandomGrid({ gridSize, blackCells, rand });
        const analysis = analyzeClusters(cells, gridSize);
        if (analysis.squares.length > 0) {
            return { cells, placementOrder, attempts: attempt, analysis };
        }
    }
    // Reaching this point is astronomically unlikely at any density in the supported range
    // (worst case, B=60, P(>=1 2x2) is still well above zero) -- this is a hard safety net,
    // not an expected code path, so it fails loudly rather than silently returning a
    // grid with no cluster for the reveal step to choke on.
    throw new Error(
        `findQualifyingRandomGrid: no qualifying grid found in ${maxAttempts} attempts ` +
        `at blackCells=${blackCells}. This should be effectively impossible; check the ` +
        `density/threshold configuration.`
    );
}

// ---------------------------------------------------------------------------
// Local-attraction generator (spec section 11-12)
// ---------------------------------------------------------------------------

/**
 * Sequential weighted placement. At each step, every empty cell's weight is
 * exp(lambda * n), where n is that cell's count of already-black 4-neighbors
 * (up/down/left/right). One empty cell is sampled proportional to its weight; repeat until
 * exactly `blackCells` cells are black.
 *
 * This produces a grid that is genuinely non-random across its ENTIRE area, not only at
 * one inserted feature -- every cell's placement was influenced by its neighbors at the
 * moment it was placed (spec section 11). An earlier candidate design ("generate randomly,
 * then force one square into an otherwise-uniform grid") was rejected for exactly this
 * reason: it would only be non-random at the one planted feature, which the "NON-RANDOM"
 * label would then misrepresent everywhere else on the grid.
 *
 * Chosen over a full Ising-model/MCMC approach for the same qualitative behavior (bias
 * toward neighbor-matching) with much less implementation risk: no burn-in or convergence
 * check needed, trivially seedable, and every placement is individually auditable (this
 * cell was chosen because it had N black neighbors at that step, weight was exp(lambda*N)).
 *
 * Cost is O(blackCells * cellCount) in the worst case (recomputing neighbor counts for all
 * remaining empty cells at every step) -- for a 20x20 grid at B=80 this is roughly 80 * 360
 * ~= 29,000 weight evaluations, comfortably sub-millisecond in practice. Not suitable for
 * much larger grids without optimization, but this exhibit's grid size is fixed (see
 * GRID_SIZE above).
 *
 * @returns {{cells: Uint8Array, placementOrder: number[]}}
 */
export function generateLocalAttractionCells({
    gridSize = GRID_SIZE,
    blackCells = DEFAULT_BLACK_CELLS,
    lambda = DEFAULT_LAMBDA,
    rand = Math.random
} = {}) {
    const cellCount = gridSize * gridSize;
    const cells = new Uint8Array(cellCount);
    const placementOrder = [];
    const empties = new Set(Array.from({ length: cellCount }, (_, i) => i));

    for (let step = 0; step < blackCells; step++) {
        const candidates = Array.from(empties);
        const weights = new Array(candidates.length);
        let total = 0;
        for (let i = 0; i < candidates.length; i++) {
            const idx = candidates[i];
            const row = Math.floor(idx / gridSize);
            const col = idx % gridSize;
            let neighborCount = 0;
            if (isBlackAt(cells, gridSize, row - 1, col)) neighborCount++;
            if (isBlackAt(cells, gridSize, row + 1, col)) neighborCount++;
            if (isBlackAt(cells, gridSize, row, col - 1)) neighborCount++;
            if (isBlackAt(cells, gridSize, row, col + 1)) neighborCount++;
            const w = Math.exp(lambda * neighborCount);
            weights[i] = w;
            total += w;
        }

        let r = rand() * total;
        let chosenIndex = candidates.length - 1; // fallback for floating-point edge case
        for (let i = 0; i < candidates.length; i++) {
            r -= weights[i];
            if (r <= 0) { chosenIndex = i; break; }
        }

        const chosenCell = candidates[chosenIndex];
        cells[chosenCell] = 1;
        placementOrder.push(chosenCell);
        empties.delete(chosenCell);
    }

    return { cells, placementOrder };
}

/**
 * Finds the 2x2 window with the fewest white cells (ties broken by scan order, which is
 * fine -- there is no meaningful difference between tied candidates). Used by the repair
 * fallback below. Returns null only if every possible window already has zero black cells,
 * which cannot happen once blackCells > 0 on any grid this module generates.
 */
function findBestRepairWindow(cells, gridSize) {
    let best = null;
    let bestWhiteCount = Infinity;
    for (let row = 0; row <= gridSize - 2; row++) {
        for (let col = 0; col <= gridSize - 2; col++) {
            let whiteCount = 0;
            const windowCells = [
                cellIndex(row, col, gridSize),
                cellIndex(row, col + 1, gridSize),
                cellIndex(row + 1, col, gridSize),
                cellIndex(row + 1, col + 1, gridSize)
            ];
            for (const idx of windowCells) if (cells[idx] === 0) whiteCount++;
            if (whiteCount > 0 && whiteCount < bestWhiteCount) {
                bestWhiteCount = whiteCount;
                best = windowCells;
            }
        }
    }
    return best;
}

/**
 * Generates a local-attraction grid and, on the rare occasions (~4% at DEFAULT_LAMBDA) that
 * no qualifying square emerged organically, repairs it: completes the nearest-to-qualifying
 * 2x2 window by flipping its white cells to black, and flips an equal number of black cells
 * elsewhere (chosen uniformly at random among cells not in the repaired window) to white, so
 * `blackCells` stays exactly fixed (spec section 12).
 *
 * Repaired cells are appended to placementOrder AFTER all organically-placed cells and
 * listed in `repairedCells`, so the rewind scrubber and any explanatory copy can represent
 * them honestly -- they were not produced by the neighbor-biased process (spec section 12,
 * section 14: "the scrubber must never misrepresent how a repaired cell arrived").
 *
 * @returns {{cells: Uint8Array, placementOrder: number[], repaired: boolean, repairedCells: number[]}}
 */
export function generateLocalAttractionGrid({
    gridSize = GRID_SIZE,
    blackCells = DEFAULT_BLACK_CELLS,
    lambda = DEFAULT_LAMBDA,
    rand = Math.random
} = {}) {
    const { cells, placementOrder } = generateLocalAttractionCells({ gridSize, blackCells, lambda, rand });

    const analysis = analyzeClusters(cells, gridSize);
    if (analysis.squares.length > 0) {
        return { cells, placementOrder, repaired: false, repairedCells: [] };
    }

    // Repair fallback.
    const window = findBestRepairWindow(cells, gridSize);
    if (!window) {
        // findBestRepairWindow can only return null if every 2x2 window already has zero
        // black cells, which is impossible once blackCells > 0 (see its own doc comment).
        // This is an unreachable-in-practice guard, not an expected path, so it fails
        // loudly rather than letting `window.filter` below throw a confusing TypeError.
        throw new Error(
            'generateLocalAttractionGrid: repair fallback found no usable window to ' +
            'complete. This should be impossible for any blackCells > 0; check ' +
            'findBestRepairWindow and the current MIN/MAX_BLACK_CELLS range.'
        );
    }
    const toBlacken = window.filter((idx) => cells[idx] === 0);
    const blackCellIndices = [];
    for (let i = 0; i < cells.length; i++) if (cells[i] === 1) blackCellIndices.push(i);
    shuffleInPlace(blackCellIndices, rand);

    const windowSet = new Set(window);
    const toWhiten = [];
    for (const idx of blackCellIndices) {
        if (toWhiten.length >= toBlacken.length) break;
        if (!windowSet.has(idx)) toWhiten.push(idx);
    }

    for (const idx of toWhiten) cells[idx] = 0;
    for (const idx of toBlacken) cells[idx] = 1;

    // Repaired cells are placed "after" every organic placement, in the order blackened:
    // remove the whitened cells from the recorded order, then append the repaired ones
    // last. toWhiten.length === toBlacken.length by construction, so the total placement
    // count stays exactly blackCells.
    const whitenedSet = new Set(toWhiten);
    const prunedOrder = placementOrder.filter((idx) => !whitenedSet.has(idx));
    const finalOrder = prunedOrder.concat(toBlacken);

    return { cells, placementOrder: finalOrder, repaired: true, repairedCells: toBlacken.slice() };
}

// ---------------------------------------------------------------------------
// Cluster detection (spec section 17)
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} SquareCluster
 * @property {number} size   Side length k (2 for a 2x2, 3 for a 3x3, ...).
 * @property {number} row    Top-left row of the square.
 * @property {number} col    Top-left col of the square.
 */

/**
 * Finds every qualifying square cluster, smallest-to-largest, by first scanning for every
 * 2x2 all-black window, then attempting to grow each hit outward (spec section 17): try to
 * extend to 3x3 (5 additional cells), then 4x4, and so on, stopping the moment an extension
 * fails. Only the largest square anchored at each growth chain is kept -- a 3x3 that
 * contains four overlapping 2x2s is reported once, as a 3x3, not as four separate 2x2s
 * (spec section 7: "detection must find the largest qualifying square, not just any 2x2").
 *
 * This smallest-to-largest order was chosen deliberately over a largest-first search:
 * starting large requires guessing a starting size and wastes work on big windows that will
 * almost always fail immediately, given how rare anything above 2x2 already is at the
 * densities this exhibit uses. It also mirrors the exhibit's own narrative -- a small,
 * ordinary-looking pattern, occasionally an unusually large one -- so the code's structure
 * matches the story it tells.
 *
 * @returns {{squares: SquareCluster[], countsBySize: Record<number, number>, largestSquare: number}}
 */
export function analyzeClusters(cells, gridSize = GRID_SIZE) {
    const squares = [];
    const countsBySize = {};
    let largestSquare = 0;

    // Track which 2x2 anchors are already accounted for by a larger square found from a
    // different anchor, so we don't double-report (e.g. a 3x3 at (r,c) covers 2x2 anchors
    // at (r,c), (r,c+1), (r+1,c), (r+1,c+1) -- only (r,c) should ever grow into it, but a
    // 2x2-only hit at, say, (r,c+1) that happens to also be part of that same 3x3 must not
    // be separately reported once the 3x3 is found).
    const claimed = new Set();

    for (let row = 0; row <= gridSize - 2; row++) {
        for (let col = 0; col <= gridSize - 2; col++) {
            const anchor = cellIndex(row, col, gridSize);
            if (claimed.has(anchor)) continue;

            const isFilled2x2 =
                isBlackAt(cells, gridSize, row, col) &&
                isBlackAt(cells, gridSize, row, col + 1) &&
                isBlackAt(cells, gridSize, row + 1, col) &&
                isBlackAt(cells, gridSize, row + 1, col + 1);
            if (!isFilled2x2) continue;

            // Grow: try k=3, 4, ... until extension fails.
            let size = 2;
            while (true) {
                const nextSize = size + 1;
                let canGrow = row + nextSize <= gridSize && col + nextSize <= gridSize;
                if (canGrow) {
                    // Check the new bottom row and right column that a (size+1)-square adds.
                    outer:
                    for (let r = row; r < row + nextSize; r++) {
                        for (let c = col; c < col + nextSize; c++) {
                            if (r < row + size && c < col + size) continue; // already known black
                            if (!isBlackAt(cells, gridSize, r, c)) { canGrow = false; break outer; }
                        }
                    }
                }
                if (canGrow) size = nextSize; else break;
            }

            squares.push({ size, row, col });
            countsBySize[size] = (countsBySize[size] || 0) + 1;
            if (size > largestSquare) largestSquare = size;

            // Mark every 2x2 anchor fully inside this square as claimed, so it is never
            // independently reported as its own smaller square.
            for (let r = row; r <= row + size - 2; r++) {
                for (let c = col; c <= col + size - 2; c++) {
                    claimed.add(cellIndex(r, c, gridSize));
                }
            }
        }
    }

    return { squares, countsBySize, largestSquare };
}

// ---------------------------------------------------------------------------
// Reveal-pair selection (spec section 8, State 1)
// ---------------------------------------------------------------------------

/**
 * Picks the single cluster to reveal first from a grid's analysis: the largest available
 * square (spec section 7 -- a 3x3+ is always shown as itself from the very first reveal,
 * never teased as a plain 2x2). If several squares share the largest size, one is chosen
 * uniformly at random via `rand` (there's no principled reason to prefer one location over
 * another, and always picking e.g. the first-scanned one would bias toward the top-left of
 * the grid).
 *
 * @returns {SquareCluster}
 */
export function pickPrimaryCluster(analysis, rand = Math.random) {
    if (analysis.squares.length === 0) {
        throw new Error('pickPrimaryCluster: analysis has no qualifying squares.');
    }
    const largest = analysis.squares.filter((sq) => sq.size === analysis.largestSquare);
    const idx = Math.floor(rand() * largest.length);
    return largest[idx];
}

/** Every cell index covered by a given square cluster, for outlining/highlighting. */
export function cellsInSquare(square, gridSize = GRID_SIZE) {
    const out = [];
    for (let r = square.row; r < square.row + square.size; r++) {
        for (let c = square.col; c < square.col + square.size; c++) {
            out.push(cellIndex(r, c, gridSize));
        }
    }
    return out;
}
